### ISSUE TITLE
Conduct initial user testing

### ISSUE THREAD

**Issue by vicfx** [nasa/openmct-map#1]
Verify the following basic functionality:

* See the planned traverse on a map
* Display one of several maps
* Max map area and resolution
* Gesture to recenter view on rover
* Zoom and pan user gestures
* Display sequence of rover positions on map, a historic rover path.
* Click on past rover position and get copyable coordinates and datetime stamp value.
* Consistent coordinate system between WARP map and VERVE
* Display waypoints as seen in VERVE, with ID labels
* Display driving plan KML
* Specify point(s) and get coordinates
* Data instrument data values on a map, aka "spray paint".
* Control what instrument data spray paint is displayed at any given time.
* User control of color ranges relative to upper and lower data limits
* Data point spreads visualized as circle blobs
* Must represent certainty/estimated confidence in spray paint
* Map shows historical and real-time data
* Map syncs to Time Conductor for historical and real-time data
* Indicate rover position (map, position alpha values, etc.) for a given timestamp
* Define and change threshold values for a given instrument.
* Visualize threshold value excessions in plot context
* Identify threshold excessions quickly in map context.
* Be able to see previous values for a given position when crossing over a previously visited point.

**Comment by VWoeltjen** [comment]
```json
[
    {
        "type": "image",
        "url": "path/to/image.png",
        "left": 10,
        "right": 20,
        "top": 0,
        "bottom": 40
    },
    {
        "type": "plan",
        "coordinates": [
            {
                "x": 47.05,
                "y": 87.55
            },
            {
                "x": 47.15,
                "y": 87.45
            },
            {
                "x": 47.1,
                "y": 87.55
            }
        ]

    },
    {
        "type": "path",
        "x": "domain-object-id",
        "y": "domain-object-id"
    },
    {
        "type": "heat",
        "x": "domain-object-id",
        "y": "domain-object-id",
        "z": "domain-object-id"
    },
    {
        "type": "point",
        "x": "domain-object-id",
        "y": "domain-object-id"
    },
    {
        "type": "points",
        "x": "domain-object-id",
        "y": "domain-object-id"
    },
    {
        "type": "camera",
        "x": "domain-object-id",
        "y": "domain-object-id"    
    }
]
```

**Comment by VWoeltjen** [comment]
Short verification procedures are presented for each feature below. Changes may be made in the Edit Properties... dialog, and by subsequently reloading the page.

* See the planned traverse on a map: Add image and plan layers to a Traverse Map. In both cases, coordinates should be provided in site frame. 
* Display one of several maps: Add/remove image layers and reload to change which image(s) are displayed.
* Max map area and resolution: Add an image layer for an image of 2000x2000 pixels or greater.
* Gesture to recenter view on rover: Add a camera layer with the same x/y telemetry points as the rover.
* Zoom and pan user gestures: Mouse wheel zoom, click-drag to pan
* Display sequence of rover positions on map, a historic rover path.: Add a "path" layer with "x" and "y" identifiers for telemetry objects corresponding to the rover's position in site frame coordinates
* Click on past rover position and get copyable coordinates and datetime stamp value.: Click on a rover position, see x/y/time appear in Inspector
* Consistent coordinate system between WARP map and VERVE: Site frame coordinates
* Display waypoints as seen in VERVE, with ID labels: Add a points layer with x/y telemetry corresponding to the X and Y positions of waypoints
* Display driving plan KML: Convert KML file to site frame coordinates and create a plan layer
* Specify point(s) and get coordinates: Hold alt and click. A point is dropped and its x/y position appears in the Inspection area
* Data instrument data values on a map, aka "spray paint".: Create a heat layer with x/y rover position telemetry objects and a z value for instrument values
* Control what instrument data spray paint is displayed at any given time.: Change the value for "z" in a heat layer
* User control of color ranges relative to upper and lower data limits: Set the "low" and "high" values  for a heat layer
* Data point spreads visualized as circle blobs: Set the "blur" and "radius" properties for a heat layer
* Must represent certainty/estimated confidence in spray paint: Zoom in until individual circles for heat layer can be seen
* Map shows historical and real-time data: Observe while Time Conductor is in real-time mode; traverse map should load with historical data visible and continue to plot additional data as it comes in
* Map syncs to Time Conductor for historical and real-time data: Change time conductor settings; observe that the traverse map updates
* Indicate rover position (map, position alpha values, etc.) for a given timestamp: Change time conductor to historical mode, add a point layer, and set the end time for the time conductor to the given timestamp of interest.
* Define and change threshold values for a given instrument: Change the "low" and "high" values for a heat layer
* Identify threshold excessions quickly in map context.: Observe color changes for the instrument
* Be able to see previous values for a given position when crossing over a previously visited point.: Zoom in until previous point or heat map circle can be selected, then click and select

**Comment by charlesh88** [comment]
Requirements checklist, ported from comment 1 above.

- [ ] See the planned traverse on a map
- [ ] Display one of several maps
- [ ] Max map area and resolution
- [ ] Gesture to recenter view on rover
- [ ] Zoom and pan user gestures
- [ ] Display sequence of rover positions on map, a historic rover path.
- [ ] Click on past rover position and get copyable coordinates and datetime stamp value.
- [ ] Consistent coordinate system between WARP map and VERVE
- [ ] Display waypoints as seen in VERVE, with ID labels
- [ ] Display driving plan KML
- [ ] Specify point(s) and get coordinates
- [ ] Data instrument data values on a map, aka "spray paint".
- [ ] Control what instrument data spray paint is displayed at any given time.
- [ ] User control of color ranges relative to upper and lower data limits
- [ ] Data point spreads visualized as circle blobs
- [ ] Must represent certainty/estimated confidence in spray paint
- [ ] Map shows historical and real-time data
- [ ] Map syncs to Time Conductor for historical and real-time data
- [ ] Indicate rover position (map, position alpha values, etc.) for a given timestamp
- [ ] Define and change threshold values for a given instrument.
- [ ] Visualize threshold value excessions in plot context
- [ ] Identify threshold excessions quickly in map context.
- [ ] Be able to see previous values for a given position when crossing over a previously visited point.

**Comment by charlesh88** [comment]
Other todos:
### Questions:
- What does attributes button in lower right do?
- The plan gets drawn with an extra point at the end, at a coordinate that is unclear where it's defined. 
### UI comments, in order of priority:
- [ ] Plan path and traverse path should be different colors or line styles.
- [ ] Dot constantly following cursor: seems to be creating problems clicking other elements. Would be better if only appears when alt key is pressed.
- [ ] View is initially zoomed in way too far. Is there a way to set this in the config, or, can we auto-zoom to bounds of the "main" image layer? 
- [ ] What is setting canvas size to a fixed area? Ideally, should dynamically be 100% h and w of viewport area.
- [ ] Need to set a background color on element ol-viewport.
- [ ] Can dots be removed? Ideally yes.
- [ ] Buttons need styling.
- [ ] Magnify +/- controls should only show on hover (local controls-style).

**Comment by larkin** [comment]
Closing, opened issues to track outstanding issues.
