### ISSUE TITLE
Controls and popup need better styling

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct-map#8]
Observed during testathon 03-30-2018:

1. Needs a little CSS love applied to coordinates bubble and local control buttons, in that order of priority. Padding on `p` element in `mct-map-popup-content` needs to be dealt with as well as text color and field styling.
![screen shot 2018-03-30 at 3 45 20 pm](https://user-images.githubusercontent.com/1056412/38156254-6a2cb596-3431-11e8-8cd7-7259c3d455c3.png)

**Comment by charlesh88** [comment]
@larkin For the markup, nice to add CSS is as follows; CSS class mods within ** marks.

For the container and buttons for the zoom controls:
````
<div class=“ol-zoom ol-unselectable ol-control **l-btn-set**”>
	<button class=“… **s-button**”>H</button>
</div>
````
For the container and buttons for our map controls:
````
<div class="mct-map-controls ol-unselectable ol-control **l-btn-set**”>
	<button class=“… **s-button**”>H</button>
</div>
````
Once this is done to the markup, I’ll still have to do some CSS overrides to turn off the “ol-“ styling.

**Comment by larkin** [comment]
@charlesh88 I have made these changes, but since it breaks the map with current styling I've pushed it to the `control-classes` branch.  Add your css changes in that branch and when it's all working just merge that branch into master & push.

I can remove the 'ol-zoom' class if you'd like?
